#!/bin/sh

# setting up colors for console output
c_end="$(git config --get-color "" "reset")"
c_green="$(git config --get-color "" "green")"
cb_green="$(git config --get-color "" "bold green")"

commit_message="$(cat "$1")"

# If an issue number exits it should be set
# before the commit message
if [ -n "$GIT_COMMIT_PREFIX" ]; then
  printf "\r\n${c_green}Prefixing commit message with ${cb_green}${GIT_COMMIT_PREFIX}${c_end}\r\n"

  # When the commit-message has no prefix it is going to be prefixed
  # Avoids doubled prefixes
  if [[ $commit_message != *$GIT_COMMIT_PREFIX* ]]; then
    echo "$GIT_COMMIT_PREFIX $commit_message" > "$1";
  fi
fi
